title:              sami blog
email:              justdoit1978@gmail.com
description:        "^^ ^ㅠ^ ^0^ ^^; ^^b ^-^"
author:             sami
baseurl:            ""
url:                "https://kwonyoungjoo.github.io"

# Build settings
markdown:           kramdown
paginate:           8
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
